paths:
  root: "UCF-101"
  annotation_path: "ucfTrainTestlist"
  frames_per_clip: 8
  step_between_clips: 2
  fold : 1
  train_dataset:
    train: True
  test_dataset:
    train: False





training:
  batch_size: 4
  num_epochs: 10


  